# Generated by Django 2.2.1 on 2019-05-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('GPS', models.CharField(max_length=200)),
                ('birdweight', models.FloatField()),
                ('foodweight', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('airquality', models.FloatField()),
                ('rain', models.FloatField()),
                ('video', models.CharField(max_length=200)),
                ('picture1', models.CharField(max_length=200)),
                ('picture2', models.CharField(max_length=200)),
                ('picture3', models.CharField(max_length=200)),
                ('picture4', models.CharField(max_length=200)),
            ],
        ),
    ]
