# Generated by Django 2.2.1 on 2019-07-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('GPS', models.CharField(max_length=200)),
                ('hoppername', models.CharField(max_length=200)),
                ('hopperweight', models.FloatField()),
                ('birdweight', models.FloatField()),
                ('feedingduration', models.FloatField()),
                ('feedingamount', models.FloatField()),
                ('temperature', models.FloatField()),
                ('rainamount', models.FloatField()),
                ('filepath', models.CharField(max_length=200)),
            ],
        ),
    ]
